[build]
builder = "NIXPACKS"
buildCommand = "npm install -g pnpm && $(npm root -g)/.bin/pnpm install --frozen-lockfile && $(npm root -g)/.bin/pnpm run build"

[deploy]
startCommand = "node dist/index.cjs"
